on:
  push:
    branches:
      - master
      - continuous_integration
  pull_request:
    branches:
      - master
      - continuous_integration
      
name: C_linter

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Make directory for artifact
      run: mkdir ${{ github.workspace }}/src/c_lint_artifact

    - name: Copy files to c_lint_artifact
      run: |
        cp ${{ github.workspace }}/src/*.c ${{ github.workspace }}/src/c_lint_artifact
    
    - name: Install clang-format
      run: |
        brew install clang-format
        
    - name: Run clang-format
      run: |
        find ${{ github.workspace }}/src/c_lint_artifact -name "*.c" | xargs clang-format --style="Google" -i

    - name: Upload C linter artifact
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: c_linter
        path: ${{ github.workspace }}/src/c_lint_artifact
