on: [push, pull_request]

name: R linter

jobs:
  lint:
    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
     
      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: enable annotations
        run: echo "::add-matcher::lintr-problem-matcher.json"

      - name: Lint
        run: if ( length(lintr::lint_package(linters = lintr::with_defaults(object_name_linter = NULL)) -> results)) { print.listof(results); quit(status=1) }
        shell: Rscript {0}
